name: sourabhm-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - gradio
      - langchain
      - openai
      - python-dotenv
      - chromadb
      - tiktoken
